// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HabitsColumns holds the columns for the "habits" table.
	HabitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// HabitsTable holds the schema information for the "habits" table.
	HabitsTable = &schema.Table{
		Name:       "habits",
		Columns:    HabitsColumns,
		PrimaryKey: []*schema.Column{HabitsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HabitsTable,
	}
)

func init() {
}
