// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/habit"
	"api/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HabitUpdate is the builder for updating Habit entities.
type HabitUpdate struct {
	config
	hooks    []Hook
	mutation *HabitMutation
}

// Where appends a list predicates to the HabitUpdate builder.
func (hu *HabitUpdate) Where(ps ...predicate.Habit) *HabitUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetName sets the "name" field.
func (hu *HabitUpdate) SetName(s string) *HabitUpdate {
	hu.mutation.SetName(s)
	return hu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (hu *HabitUpdate) SetNillableName(s *string) *HabitUpdate {
	if s != nil {
		hu.SetName(*s)
	}
	return hu
}

// SetDescription sets the "description" field.
func (hu *HabitUpdate) SetDescription(s string) *HabitUpdate {
	hu.mutation.SetDescription(s)
	return hu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (hu *HabitUpdate) SetNillableDescription(s *string) *HabitUpdate {
	if s != nil {
		hu.SetDescription(*s)
	}
	return hu
}

// ClearDescription clears the value of the "description" field.
func (hu *HabitUpdate) ClearDescription() *HabitUpdate {
	hu.mutation.ClearDescription()
	return hu
}

// SetCreatedAt sets the "created_at" field.
func (hu *HabitUpdate) SetCreatedAt(t time.Time) *HabitUpdate {
	hu.mutation.SetCreatedAt(t)
	return hu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hu *HabitUpdate) SetNillableCreatedAt(t *time.Time) *HabitUpdate {
	if t != nil {
		hu.SetCreatedAt(*t)
	}
	return hu
}

// Mutation returns the HabitMutation object of the builder.
func (hu *HabitUpdate) Mutation() *HabitMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HabitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HabitUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HabitUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HabitUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hu *HabitUpdate) check() error {
	if v, ok := hu.mutation.Name(); ok {
		if err := habit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Habit.name": %w`, err)}
		}
	}
	return nil
}

func (hu *HabitUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := hu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(habit.Table, habit.Columns, sqlgraph.NewFieldSpec(habit.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.Name(); ok {
		_spec.SetField(habit.FieldName, field.TypeString, value)
	}
	if value, ok := hu.mutation.Description(); ok {
		_spec.SetField(habit.FieldDescription, field.TypeString, value)
	}
	if hu.mutation.DescriptionCleared() {
		_spec.ClearField(habit.FieldDescription, field.TypeString)
	}
	if value, ok := hu.mutation.CreatedAt(); ok {
		_spec.SetField(habit.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{habit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HabitUpdateOne is the builder for updating a single Habit entity.
type HabitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HabitMutation
}

// SetName sets the "name" field.
func (huo *HabitUpdateOne) SetName(s string) *HabitUpdateOne {
	huo.mutation.SetName(s)
	return huo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (huo *HabitUpdateOne) SetNillableName(s *string) *HabitUpdateOne {
	if s != nil {
		huo.SetName(*s)
	}
	return huo
}

// SetDescription sets the "description" field.
func (huo *HabitUpdateOne) SetDescription(s string) *HabitUpdateOne {
	huo.mutation.SetDescription(s)
	return huo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (huo *HabitUpdateOne) SetNillableDescription(s *string) *HabitUpdateOne {
	if s != nil {
		huo.SetDescription(*s)
	}
	return huo
}

// ClearDescription clears the value of the "description" field.
func (huo *HabitUpdateOne) ClearDescription() *HabitUpdateOne {
	huo.mutation.ClearDescription()
	return huo
}

// SetCreatedAt sets the "created_at" field.
func (huo *HabitUpdateOne) SetCreatedAt(t time.Time) *HabitUpdateOne {
	huo.mutation.SetCreatedAt(t)
	return huo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (huo *HabitUpdateOne) SetNillableCreatedAt(t *time.Time) *HabitUpdateOne {
	if t != nil {
		huo.SetCreatedAt(*t)
	}
	return huo
}

// Mutation returns the HabitMutation object of the builder.
func (huo *HabitUpdateOne) Mutation() *HabitMutation {
	return huo.mutation
}

// Where appends a list predicates to the HabitUpdate builder.
func (huo *HabitUpdateOne) Where(ps ...predicate.Habit) *HabitUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HabitUpdateOne) Select(field string, fields ...string) *HabitUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Habit entity.
func (huo *HabitUpdateOne) Save(ctx context.Context) (*Habit, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HabitUpdateOne) SaveX(ctx context.Context) *Habit {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HabitUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HabitUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (huo *HabitUpdateOne) check() error {
	if v, ok := huo.mutation.Name(); ok {
		if err := habit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Habit.name": %w`, err)}
		}
	}
	return nil
}

func (huo *HabitUpdateOne) sqlSave(ctx context.Context) (_node *Habit, err error) {
	if err := huo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(habit.Table, habit.Columns, sqlgraph.NewFieldSpec(habit.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Habit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, habit.FieldID)
		for _, f := range fields {
			if !habit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != habit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.Name(); ok {
		_spec.SetField(habit.FieldName, field.TypeString, value)
	}
	if value, ok := huo.mutation.Description(); ok {
		_spec.SetField(habit.FieldDescription, field.TypeString, value)
	}
	if huo.mutation.DescriptionCleared() {
		_spec.ClearField(habit.FieldDescription, field.TypeString)
	}
	if value, ok := huo.mutation.CreatedAt(); ok {
		_spec.SetField(habit.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Habit{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{habit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
