basePath: /
definitions:
  ent.Habit:
    properties:
      created_at:
        description: CreatedAt holds the value of the "created_at" field.
        type: string
      description:
        description: Description holds the value of the "description" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      name:
        description: Name holds the value of the "name" field.
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API for a habit tracker app.
  title: Habit Tracker API
  version: "1.0"
paths:
  /habits:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ent.Habit'
            type: array
      summary: Get all habits
    post:
      consumes:
      - application/json
      parameters:
      - description: Habit to create
        in: body
        name: habit
        required: true
        schema:
          $ref: '#/definitions/ent.Habit'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Habit'
      summary: Create a new habit
  /habits/{id}:
    delete:
      parameters:
      - description: Habit ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Delete a habit
    get:
      parameters:
      - description: Habit ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Habit'
      summary: Get a single habit
    put:
      consumes:
      - application/json
      parameters:
      - description: Habit ID
        in: path
        name: id
        required: true
        type: integer
      - description: Habit to update
        in: body
        name: habit
        required: true
        schema:
          $ref: '#/definitions/ent.Habit'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Habit'
      summary: Update a habit
swagger: "2.0"
